version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
     - "5000:5000"
    depends_on:
      - redis
  redis:
    image: redisfab/grocerydemo:latest
    command: redis-server /data/redis.conf
    ports:
     - "6379:6379"
