version: "3.9"
services:
  app:
    build: app
    ports:
     - "5000:5000"
  redis:
    image: redislabs/groceriesdemo:latest
    command: redis-server /data/redis.conf
    ports:
     - "6379:6379"
