version: "3.9"
services:
  app:
    build: ./app
    ports:
      - "5000:5000"
  redis:
    command: redis-server /data/redis.conf
    image: "redislabs/redisearch:2.6.1"
    volumes:
       - "./redis:/data"
    ports:
      - "6379:6379"
